### ISSUE TITLE
autoconf is a missing dependency

### ISSUE THREAD

**Issue by skorasaurus** [lolilolicon/xrectsel#3]
Hi, 

Thanks for making this. I'm installing this on ubuntu 14.04 and had into install autoconf in order to install xrectsel. 

Before installing autoconf, I received this error: 
```./bootstrap 
./bootstrap: line 1: autoreconf: command not found
```

**Comment by 7belrhalmia** [comment]
@skorasaurus   
     sudo apt-get install dh-autoreconf

**Comment by nclundsten** [comment]
*found this useful

**Comment by edouard-lopez** [comment]
you will also need to intall `libx11-dev`

    apt install libx11-dev
